parameters:
    xls.phpexcel.class: PHPExcel
    xls.service.class: Liuggio\ExcelBundle\Service\ExcelContainer

services:
    xls.phpexcel:
      class: %xls.phpexcel.class%

    xls.service:
      class: Liuggio\ExcelBundle\Service\Excel
      arguments: ["@xls.phpexcel"]

    xls.excel5:
      class: Liuggio\ExcelBundle\Service\Excel
      arguments: ["@xls.phpexcel" ]
      calls:
        - [ setType, [ "Excel5" ] ]

    xls.excel2007:
      class: Liuggio\ExcelBundle\Service\Excel
      arguments: ["@xls.phpexcel"]
      calls:
        - [ setType, [ "Excel2007" ] ]
